//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Breakfast_Cards_Manage_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public string YearMonth { get; set; }
        public Nullable<int> Intune { get; set; }
        public Nullable<int> Office { get; set; }
        public Nullable<int> SCCM { get; set; }
        public Nullable<int> Teams { get; set; }
        public Nullable<int> POD1 { get; set; }
        public Nullable<int> POD2 { get; set; }
        public Nullable<int> S500_1 { get; set; }
        public Nullable<int> S500_2 { get; set; }
        public Nullable<int> SharePoint { get; set; }
    }
}
